version: '3'
services:

    ghost:
        image: ghost
        volumes:
          - /data/local/blog:/var/lib/ghost
        environment:
          - VIRTUAL_HOST=blog.bambil.ml
          - VIRTUAL_PORT=2368
        networks: [edge]

networks:
    edge:
        external: true
